/**
 * Jacques GUI Types
 *
 * These types are duplicated from @jacques/core for browser compatibility.
 * The core package uses Node.js APIs which aren't available in browsers.
 */

export interface AutoCompactStatus {
  enabled: boolean;
  threshold: number;
  bug_threshold: number | null;
}

export interface TerminalIdentity {
  term_program?: string;
  tty?: string;
  window_id?: string;
  terminal_pid?: string;
}

export interface ContextMetrics {
  used_percentage: number;
  context_window_size: number;
  total_input_tokens: number;
  total_output_tokens: number;
  is_estimate?: boolean;
}

export interface ModelInfo {
  id?: string;
  display_name?: string;
  provider?: string;
}

export interface WorkspaceInfo {
  project_dir?: string;
}

export type SessionSource = 'claude_code' | 'cursor' | string;

export interface Session {
  session_id: string;
  source: SessionSource;
  cwd: string;
  project: string;
  session_title: string | null;
  terminal?: TerminalIdentity;
  context_metrics: ContextMetrics | null;
  model: ModelInfo | null;
  workspace: WorkspaceInfo | null;
  autocompact: AutoCompactStatus | null;
  status: 'idle' | 'working' | 'active';
  last_activity: number;
  registered_at: number;
  transcript_path?: string;
}

// Server message types
export interface InitialStateMessage {
  type: 'initial_state';
  sessions: Session[];
  focused_session_id: string | null;
}

export interface SessionUpdateMessage {
  type: 'session_update';
  session: Session;
}

export interface SessionRemovedMessage {
  type: 'session_removed';
  session_id: string;
}

export interface FocusChangedMessage {
  type: 'focus_changed';
  session_id: string | null;
  session: Session | null;
}

export interface AutoCompactToggledMessage {
  type: 'autocompact_toggled';
  enabled: boolean;
  warning?: string;
}

/**
 * Claude operation (e.g., LLM handoff)
 */
export interface ClaudeOperation {
  /** Unique identifier for this operation */
  id: string;
  /** ISO timestamp when operation started */
  timestamp: string;
  /** Operation type (e.g., "llm-handoff") */
  operation: string;
  /** Phase: "start" when beginning, "complete" when done */
  phase: 'start' | 'complete';
  /** Input tokens used by the LLM */
  inputTokens: number;
  /** Output tokens generated by the LLM */
  outputTokens: number;
  /** Total tokens (input + output) */
  totalTokens: number;
  /** Cache read tokens (if any) */
  cacheReadTokens?: number;
  /** Duration in milliseconds */
  durationMs: number;
  /** Whether the operation succeeded */
  success: boolean;
  /** Error message if operation failed */
  errorMessage?: string;
  /** Character count of user prompt */
  userPromptChars: number;
  /** Character count of system prompt */
  systemPromptChars: number;
  /** Estimated tokens for user prompt (~4 chars/token) */
  userPromptTokensEst?: number;
  /** Estimated tokens for system prompt (~4 chars/token) */
  systemPromptTokensEst?: number;
  /** Output content length (chars) */
  outputLength?: number;
  /** Truncated preview of user prompt */
  userPromptPreview?: string;
  /** Truncated preview of system prompt */
  systemPromptPreview?: string;
  /** Tools called during this operation (for "complete" phase) */
  toolsCalled?: string[];
}

/**
 * Debug data for a Claude operation (fetched separately)
 */
export interface ClaudeOperationDebug {
  operationId: string;
  timestamp: string;
  userPrompt: string;
  systemPrompt: string;
  cliArgs: string[];
  cliEvents: unknown[];
  response?: string;
}

export interface ClaudeOperationMessage {
  type: 'claude_operation';
  operation: ClaudeOperation;
}

/**
 * API log entry
 */
export interface ApiLog {
  /** HTTP method (GET, POST, DELETE) */
  method: string;
  /** Request path (e.g., /api/sources/status) */
  path: string;
  /** HTTP status code */
  status: number;
  /** Request duration in milliseconds */
  durationMs: number;
  /** Timestamp when request completed */
  timestamp: number;
}

export interface ApiLogMessage {
  type: 'api_log';
  method: string;
  path: string;
  status: number;
  durationMs: number;
  timestamp: number;
}

// ─── Chat Message Types ───────────────────────────────────────

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  /** Tool names used during this response */
  tools?: string[];
  /** Whether this message is still streaming */
  isStreaming?: boolean;
}

export interface CatalogItem {
  id: string;
  name: string;
  path: string;
  source: string;
  sourceFile: string;
  addedAt: string;
  description?: string;
  sizeBytes: number;
  tags?: string[];
}

export interface CatalogPlanEntry {
  id: string;
  title: string;
  filename: string;
  path: string;
  contentHash?: string;
  createdAt: string;
  updatedAt: string;
  sessions: string[];
}

export interface CatalogSessionEntry {
  id: string;
  title: string;
  filename: string;
  path: string;
  savedAt: string;
  startedAt: string;
  endedAt: string;
  durationMinutes: number;
  messageCount: number;
  toolCallCount: number;
  technologies: string[];
}

export interface ProjectCatalog {
  context: CatalogItem[];
  plans: CatalogPlanEntry[];
  sessions: CatalogSessionEntry[];
  updatedAt: string;
}

// Chat WS message types (server → client)

export interface ChatDeltaMessage {
  type: 'chat_delta';
  projectPath: string;
  text: string;
}

export interface ChatToolEventMessage {
  type: 'chat_tool_event';
  projectPath: string;
  toolName: string;
}

export interface ChatCompleteMessage {
  type: 'chat_complete';
  projectPath: string;
  fullText: string;
  inputTokens: number;
  outputTokens: number;
}

export interface ChatErrorMessage {
  type: 'chat_error';
  projectPath: string;
  reason: string;
  message: string;
}

export interface CatalogUpdatedMessage {
  type: 'catalog_updated';
  projectPath: string;
  action: string;
  itemId?: string;
}

export type ServerMessage =
  | InitialStateMessage
  | SessionUpdateMessage
  | SessionRemovedMessage
  | FocusChangedMessage
  | AutoCompactToggledMessage
  | ClaudeOperationMessage
  | ApiLogMessage
  | ChatDeltaMessage
  | ChatToolEventMessage
  | ChatCompleteMessage
  | ChatErrorMessage
  | CatalogUpdatedMessage;

// Conversation types for the viewer

export interface TokenInfo {
  input?: number;
  output?: number;
  cacheCreation?: number;
  cacheRead?: number;
}

export interface ConversationMessage {
  id: string;
  role: 'user' | 'assistant';
  timestamp: number;
  content: MessageContent[];
  tokens?: TokenInfo;
  model?: string;
  durationMs?: number;
  costUSD?: number;
}

export type MessageContent =
  | TextContent
  | ThinkingContent
  | ToolUseContent
  | ToolResultContent
  | CodeContent
  | AgentProgressContent
  | BashProgressContent
  | MCPProgressContent
  | WebSearchContent;

export interface TextContent {
  type: 'text';
  text: string;
}

export interface ThinkingContent {
  type: 'thinking';
  text: string;
}

export interface ToolUseContent {
  type: 'tool_use';
  id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface ToolResultContent {
  type: 'tool_result';
  tool_use_id: string;
  content: string;
  is_error?: boolean;
}

export interface CodeContent {
  type: 'code';
  language?: string;
  code: string;
}

export interface AgentProgressContent {
  type: 'agent_progress';
  prompt?: string;
  agentId?: string;
  messageType?: 'user' | 'assistant';
  messageContent?: unknown[];
  /** Token count from archived subagent (if available) */
  tokenCount?: number;
  /** Message count from archived subagent (if available) */
  messageCount?: number;
  /** Model used by the subagent (if available) */
  model?: string;
  /** Agent type: "Explore", "Plan", "general-purpose", etc. */
  agentType?: string;
  /** Short description of the agent's task */
  agentDescription?: string;
}

export interface BashProgressContent {
  type: 'bash_progress';
  output?: string;
  fullOutput?: string;
  elapsedSeconds?: number;
  totalLines?: number;
}

export interface MCPProgressContent {
  type: 'mcp_progress';
  status?: string;
  serverName?: string;
  toolName?: string;
}

export interface WebSearchContent {
  type: 'web_search';
  searchType?: 'query' | 'results';
  query?: string;
  resultCount?: number;
  /** URLs from web search results */
  urls?: Array<{ title: string; url: string }>;
}

export interface SavedConversation {
  id: string;
  /** Session ID for looking up subagent conversations */
  sessionId?: string;
  title: string;
  project: string;
  date: string;
  messages: ConversationMessage[];
  metadata: {
    messageCount: number;
    toolCallCount: number;
    estimatedTokens: number;
    actualTokens?: TokenInfo;
    technologies?: string[];
    filesModified?: string[];
    /** Subagent summary for token tracking */
    subagents?: {
      count: number;
      totalTokens: number;
      ids: string[];
    };
    /** Whether auto-compact occurred during this session */
    hadAutoCompact?: boolean;
    /** Timestamp when auto-compact occurred (ISO string) */
    autoCompactAt?: string;
  };
}

/**
 * Session badges for display in Dashboard session cards
 * Provides rich metadata extracted from the session transcript
 */
export interface SessionBadges {
  /** Number of plans detected in the session */
  planCount: number;
  /** Number of subagents used */
  agentCount: number;
  /** Breakdown of agent types */
  agentTypes: {
    explore: number;
    plan: number;
    general: number;
  };
  /** Number of files modified (Write/Edit tool calls) */
  fileCount: number;
  /** Number of MCP tool calls */
  mcpCount: number;
  /** Number of web searches */
  webSearchCount: number;
  /** Session mode: planning if EnterPlanMode was called, execution if started with plan */
  mode: 'planning' | 'execution' | null;
  /** Whether auto-compact occurred during this session */
  hadAutoCompact: boolean;
}
