#!/usr/bin/env tsx
/**
 * Convert PNG mascot to ANSI art
 *
 * Uses Jimp to read the image and convert to ANSI art using true color codes.
 * Processes 2 rows at a time using the ▀ (upper half block) character.
 * Top pixel = foreground color, bottom pixel = background color.
 */

import Jimp from 'jimp';
import { promises as fs } from 'fs';
import path from 'path';

const INPUT_IMAGE = path.resolve(process.cwd(), '../assets/jacminihigh.png');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/assets/mascot-ansi.ts');

interface RGB {
  r: number;
  g: number;
  b: number;
  a: number;
}

/**
 * Get RGB values from a pixel
 */
function getPixelRGB(image: Jimp, x: number, y: number): RGB {
  const color = image.getPixelColor(x, y);
  const rgba = Jimp.intToRGBA(color);
  return {
    r: rgba.r,
    g: rgba.g,
    b: rgba.b,
    a: rgba.a,
  };
}

/**
 * Check if pixel is transparent
 */
function isTransparent(pixel: RGB): boolean {
  return pixel.a < 128;
}

/**
 * Convert RGB to ANSI foreground color code
 */
function rgbToForeground(r: number, g: number, b: number): string {
  return `\x1b[38;2;${r};${g};${b}m`;
}

/**
 * Convert RGB to ANSI background color code
 */
function rgbToBackground(r: number, g: number, b: number): string {
  return `\x1b[48;2;${r};${g};${b}m`;
}

/**
 * Reset ANSI codes
 */
const RESET = '\x1b[0m';

/**
 * Convert image to ANSI art
 */
async function convertToAnsi(): Promise<string> {
  console.log('Loading image:', INPUT_IMAGE);
  const image = await Jimp.read(INPUT_IMAGE);

  const width = image.getWidth();
  const height = image.getHeight();

  console.log(`Image dimensions: ${width}x${height}`);

  const lines: string[] = [];

  // Process 2 rows at a time (top pixel = foreground, bottom pixel = background)
  for (let y = 0; y < height; y += 2) {
    let line = '';

    for (let x = 0; x < width; x++) {
      const topPixel = getPixelRGB(image, x, y);
      const bottomPixel = y + 1 < height ? getPixelRGB(image, x, y + 1) : { r: 0, g: 0, b: 0, a: 0 };

      const topTransparent = isTransparent(topPixel);
      const bottomTransparent = isTransparent(bottomPixel);

      if (topTransparent && bottomTransparent) {
        // Both transparent - use space
        line += ' ';
      } else if (topTransparent && !bottomTransparent) {
        // Top transparent, bottom has color - use lower half block (▄)
        line += rgbToForeground(bottomPixel.r, bottomPixel.g, bottomPixel.b);
        line += '▄';
        line += RESET;
      } else if (!topTransparent && bottomTransparent) {
        // Top has color, bottom transparent - use upper half block (▀)
        line += rgbToForeground(topPixel.r, topPixel.g, topPixel.b);
        line += '▀';
        line += RESET;
      } else {
        // Both have color - use upper half block with background
        line += rgbToForeground(topPixel.r, topPixel.g, topPixel.b);
        line += rgbToBackground(bottomPixel.r, bottomPixel.g, bottomPixel.b);
        line += '▀';
        line += RESET;
      }
    }

    lines.push(line);
  }

  return lines.join('\n');
}

/**
 * Main execution
 */
async function main() {
  try {
    console.log('Converting mascot to ANSI art...');
    const ansiArt = await convertToAnsi();

    // Generate TypeScript file
    const output = `/**
 * ANSI Art Mascot
 *
 * Auto-generated from jacsub.png
 * DO NOT EDIT THIS FILE MANUALLY - run \`npm run convert-mascot\` instead
 */

export const MASCOT_ANSI = \`${ansiArt}\`;
`;

    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    await fs.mkdir(outputDir, { recursive: true });

    // Write file
    await fs.writeFile(OUTPUT_FILE, output, 'utf-8');

    console.log('✓ ANSI art generated:', OUTPUT_FILE);
    console.log(`  Lines: ${ansiArt.split('\n').length}`);
  } catch (error) {
    console.error('Failed to convert mascot:', error);
    process.exit(1);
  }
}

main();
